openapi: 3.0.0
info:
  title: PN-ExternalRegistries REST APIs
  description: |-
    Nell’ambito del progetto Piattaforme Notifiche, il componente PN-ExternalRegistries si occuperà di recuperare i dati dalle banche dati esterne previste. Tali banche dati esporranno delle interfacce web verso il componente PN-External Registries, accessibili tramite piattaforma di interoperabilità.
  version: 1.0.0
servers:
- url: http://127.0.0.1
tags:
- name: getAddressANPR
  description: Il servizio viene invocato per ottenere la residenza presente in ANPR per un cittadino, alla data di riferimento della richiesta.
- name: getDigitalAddressINAD
  description: Consente di ottenere il domicilio digitale corrispondente al codice fiscale al momento della consultazione e, in caso di domicilio digitale eletto in qualità di Professionista, anche l'attività professionale esercitata.
- name: checkTaxId
  description: Questo servizio ritorna la validità e l’esistenza di un dato codice fiscale descritta da un campo di ritorno booleano nell’oggetto json di response
paths:
  /getAddressANPR:
    post:
      tags:
      - getAddressANPR
      summary: 'Il servizio viene invocato per ottenere la residenza presente in ANPR per un cittadino, alla data di riferimento della richiesta'
      description: 'Il servizio viene invocato per ottenere la residenza presente in ANPR per un cittadino, alla data di riferimento della richiesta'
      operationId: getAddressANPR
      requestBody:
        description: Il servizio viene invocato per ottenere la residenza presente in ANPR per un cittadino, alla data di riferimento della richiesta
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetAddressANPRRequestBody'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAddressANPROK'
        "400":
          description: Caso d'uso invalido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
        "404":
          description: Caso d'uso non trovato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'        
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'        
  /checkTaxId:
    post:
      tags:
      - checkTaxId
      summary: 'Questo servizio ritorna la validità e l’esistenza di un dato codice fiscale descritta da un campo di ritorno booleano nell’oggetto json di response'
      description: 'Questo servizio ritorna la validità e l’esistenza di un dato codice fiscale descritta da un campo di ritorno booleano nell’oggetto json di response'
      operationId: checkTaxId
      requestBody:
        description: Effettua la ricerca di un codice fiscale
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckTaxIdRequestBody'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckTaxIdOK'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
  /getDigitalAddressINAD:
    post:
      tags:
        - getDigitalAddressINAD
      summary: 'Consente di ottenere il domicilio digitale corrispondente al codice fiscale al momento della consultazione e, in caso di domicilio digitale eletto in qualità di Professionista, anche l''attività professionale esercitata.'
      description: 'Consente di ottenere il domicilio digitale corrispondente al codice fiscale al momento della consultazione e, in caso di domicilio digitale eletto in qualità di Professionista, anche l''attività professionale esercitata.'
      operationId: getDigitalAddressINAD
      requestBody:
        description: Consente di ottenere il domicilio digitale corrispondente al codice fiscale al momento della consultazione e, in caso di domicilio digitale eletto in qualità di Professionista, anche l'attività professionale esercitata.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetDigitalAddressINADRequestBody'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDigitalAddressINADOK'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
components:
  schemas:
    CheckTaxIdRequestBody:
      type: object
      properties:
        filter:
          type: object
          properties:
            taxId:
              type: string
    CheckTaxIdOK:
      type: object
      properties:
        taxId:
          type: string
        isValid:
          type: boolean
        errorCode:
            type: string
            enum: [B001_CHECK_TAX_ID_ERR01, B001_CHECK_TAX_ID_ERR02, B001_CHECK_TAX_ID_ERR03]
            description: >
              Error codes:
              
              
              _'B001_CHECK_TAX_ID_ERR01'_: CODICE FISCALE VALIDO NON UTILIZZABILE
              
              
              _'B001_CHECK_TAX_ID_ERR02'_: CODICE FISCALE NON VALIDO AGGIORNATO IN ALTRO
              
              
              _'B001_CHECK_TAX_ID_ERR03'_: CODICE FISCALE NON VALIDO
    GetAddressANPRRequestBody:
      type: object
      properties:
        filter:
          type: object
          properties:
            taxId:
              type: string
    GetAddressANPROK:
      type: object
      properties:
        residentialAddresses:
          type: array
          items:
            $ref: '#/components/schemas/ResidentialAddress'
    ResidentialAddress:
      type: object
      properties:
        description:
          type: string
        at:
          type: string
        address:
          type: string
        zip:
          type: string
        municipality:
          type: string
        municipalityDetails:
          type: string
        province:
          type: string
        foreignState:
          type: string
    GetDigitalAddressINADRequestBody:
      type: object
      properties:
        filter:
          type: object
          properties:
            taxId:
              type: string
            practicalReference:
              type: string
              description: 'Riferimento del procedimento amministrativo per il quale si richiede l''estrazione'
    GetDigitalAddressINADOK:
      type: object
      properties:
        taxId:
          type: string
        since:
          type: string
          format: date-time
        digitalAddress:
          type: array
          items:
            $ref: '#/components/schemas/DigitalAddress'
    DigitalAddress:
      type: object
      properties:
        digitalAddress:
          type: string
        practicedProfession:
          type: string
        usageInfo:
          $ref: '#/components/schemas/UsageInfo'
    UsageInfo:
      type: object
      properties:
        motivation:
          type: string
        dateEndValidity:
          type: string
          format: date-time
    ResponseError:
      type: object
      properties:
        status:
          type: integer
        title:
          type: string
        detail:
          type: string
        traceId:
          type: string
        timestamp:
          type: integer
        errors:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
              element:
                type: string
              detail:
                type: string
