openapi: 3.0.0
info:
  title: PN-ExternalRegistries REST APIs
  description: |-
    Nell’ambito del progetto Piattaforme Notifiche, il componente PN-ExternalRegistries si occuperà di recuperare i dati dalle banche dati esterne previste. Tali banche dati esporranno delle interfacce web verso il componente PN-External Registries, accessibili tramite piattaforma di interoperabilità.
  version: 1.0.0
servers:
- url: http://127.0.0.1
tags:
- name: getAddressANPR
  description: Il servizio viene invocato per ottenere la residenza presente in ANPR per un cittadino, alla data di riferimento della richiesta.
paths:
  /getAddressANPR:
    post:
      tags:
      - getAddressANPR
      summary: 'Il servizio viene invocato per ottenere la residenza presente in ANPR per un cittadino, alla data di riferimento della richiesta'
      description: 'Il servizio viene invocato per ottenere la residenza presente in ANPR per un cittadino, alla data di riferimento della richiesta'
      operationId: getAddressANPR
      requestBody:
        description: Il servizio viene invocato per ottenere la residenza presente in ANPR per un cittadino, alla data di riferimento della richiesta
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetAddressANPRRequestBody'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAddressANPROK'
        "400":
          description: Caso d'uso invalido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAddressANPRError'
        "404":
          description: Caso d'uso non trovato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAddressANPRError'        
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAddressANPRError'                
components:
  schemas:
    GetAddressANPRRequestBody:
      type: object
      properties:
        filter:
          type: object
          properties:
            taxId:
              type: string
    GetAddressANPROK:
      type: object
      properties:
        residentialAddresses:
          type: array
          items:
            type: object
            properties:
              description:
                type: string
              at:
                type: string
              address:
                type: string
              zip:
                type: string
              municipality:
                type: string
              municipalityDetails:
                type: string
              province:
                type: string
              foreignState:
                type: string
    GetAddressANPRError:
      type: object
      properties:
        status:
          type: integer
        title:
          type: string
        detail:
          type: string
        traceId:
          type: string
        timestamp:
          type: integer
        errors:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
              element:
                type: string
              detail:
                type: string