openapi: 3.0.0
info:
  title: PN-ExternalRegistries REST APIs
  description: |-
    Nell’ambito del progetto Piattaforme Notifiche, il componente PN-ExternalRegistries si occuperà di recuperare i dati dalle banche dati esterne previste. Tali banche dati esporranno delle interfacce web verso il componente PN-External Registries, accessibili tramite piattaforma di interoperabilità.
  version: 1.0.0
servers:
- url: http://127.0.0.1
tags:
- name: checkTaxId
  description: Questo servizio ritorna la validità e l’esistenza di un dato codice fiscale descritta da un campo di ritorno booleano nell’oggetto json di response
paths:
  /checkTaxId:
    post:
      tags:
      - checkTaxId
      summary: 'Questo servizio ritorna la validità e l’esistenza di un dato codice fiscale descritta da un campo di ritorno booleano nell’oggetto json di response'
      description: 'Questo servizio ritorna la validità e l’esistenza di un dato codice fiscale descritta da un campo di ritorno booleano nell’oggetto json di response'
      operationId: checkTaxId
      requestBody:
        description: Effettua la ricerca di un codice fiscale
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckTaxIdRequestBody'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckTaxIdOK'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckTaxIdError'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckTaxIdError'
components:
  schemas:
    CheckTaxIdRequestBody:
      type: object
      properties:
        filter:
          type: object
          properties:
            taxId:
              type: string
    CheckTaxIdOK:
      type: object
      properties:
        taxId:
          type: string
        isValid:
          type: boolean
        errorCode:
            type: string
            enum: [B001_CHECK_TAX_ID_ERR01, B001_CHECK_TAX_ID_ERR02, B001_CHECK_TAX_ID_ERR03]
            description: >
              Error codes:
              
              
              _'B001_CHECK_TAX_ID_ERR01'_: CODICE FISCALE VALIDO NON UTILIZZABILE
              
              
              _'B001_CHECK_TAX_ID_ERR02'_: CODICE FISCALE NON VALIDO AGGIORNATO IN ALTRO
              
              
              _'B001_CHECK_TAX_ID_ERR03'_: CODICE FISCALE NON VALIDO
    CheckTaxIdError:
      type: object
      properties:
        status:
          type: integer
        title:
          type: string
        detail:
          type: string
        traceId:
          type: string
        timestamp:
          type: integer
        errors:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
              element:
                type: string
              detail:
                type: string