openapi: 3.0.0
info:
  title: PN-ExternalRegistries REST APIs
  description: |-
    Nell’ambito del progetto Piattaforme Notifiche, il componente PN-ExternalRegistries si occuperà di recuperare i dati dalle banche dati esterne previste. Tali banche dati esporranno delle interfacce web verso il componente PN-External Registries, accessibili tramite piattaforma di interoperabilità.
  version: 1.0.0
servers:
  - url: http://127.0.0.1
tags:
  - name: getDigitalAddressINAD
    description: Consente di ottenere il domicilio digitale corrispondente al codice fiscale al momento della consultazione e, in caso di domicilio digitale eletto in qualità di Professionista, anche l'attività professionale esercitata.
paths:
  /getDigitalAddressINAD:
    post:
      tags:
        - getDigitalAddressINAD
      summary: 'Consente di ottenere il domicilio digitale corrispondente al codice fiscale al momento della consultazione e, in caso di domicilio digitale eletto in qualità di Professionista, anche l''attività professionale esercitata.'
      description: 'Consente di ottenere il domicilio digitale corrispondente al codice fiscale al momento della consultazione e, in caso di domicilio digitale eletto in qualità di Professionista, anche l''attività professionale esercitata.'
      operationId: getDigitalAddressINAD
      requestBody:
        description: Consente di ottenere il domicilio digitale corrispondente al codice fiscale al momento della consultazione e, in caso di domicilio digitale eletto in qualità di Professionista, anche l'attività professionale esercitata.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetDigitalAddressINADRequestBody'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDigitalAddressINADOK'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDigitalAddressINADError'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDigitalAddressINADError'
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDigitalAddressINADError'
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDigitalAddressINADError'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDigitalAddressINADError'
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDigitalAddressINADError'
components:
  schemas:
    GetDigitalAddressINADRequestBody:
      type: object
      properties:
        filter:
          type: object
          properties:
            taxId:
              type: string
            practicalReference:
              type: string
              description: 'Riferimento del procedimento amministrativo per il quale si richiede l''estrazione'
    GetDigitalAddressINADOK:
      type: object
      properties:
        taxId:
          type: string
        since:
          type: string
          format: date-time
        digitalAddress:
          type: array
          items:
            type: object
            properties:
              digitalAddress:
                type: string
              practicedProfession:
                type: string
              usageInfo:
                type: object
                properties:
                  motivation:
                    type: string
                    enum: [CESSAZIONE_UFFICIO, CESSAZIONE_VOLONTARIA]
                  dateEndValidity:
                    type: string
                    format: date-time
    GetDigitalAddressINADError:
      type: object
      properties:
        status:
          type: integer
        title:
          type: string
        detail:
          type: string
        traceId:
          type: string
        timestamp:
          type: integer
        errors:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
              element:
                type: string
              detail:
                type: string
