logging.config=classpath:logback-base.xml
spring.application.name = pn-national-registries
spring.main.web-application-type=REACTIVE

aws.region=eu-south-1
server.port=8080

# Fix null object in serialization
spring.jackson.default-property-inclusion = NON_NULL

# AdE Legal
pn.national.registries.ade-legal.base-path = ${PN_NATIONAL_REGISTRY_ADE_LEGAL_BASE_URL}
pn.national.registries.ade.auth = ${PN_NATIONAL_REGISTRY_ADE_AUTH:TEST}
pn.national.registries.ade.legal.name.id = ${PN_NATIONAL_REGISTRY_ADE_LEGAL_NAME_ID:TEST}
pn.national.registries.ade.legal.trust.secret = ${PN_NATIONAL_REGISTRY_ADE_LEGAL_TRUST_SECRET:TEST}

# AdE CheckCF
pn.national.registries.ade-check-cf.base-path = ${PN_NATIONAL_REGISTRY_ADE_CHECK_CF_BASE_URL}
pn.national.registries.pdnd.ade-check-cf.secret = ${PN_NATIONAL_REGISTRY_ADE_CHECK_CF_PDND_CLIENT_SECRET}
pn.national.registries.trust.ade-check-cf.secret = ${PN_NATIONAL_REGISTRY_ADE_CHECK_CF_TRUST_SECRET}

# INAD
pn.national.registries.inad.base-path = ${PN_NATIONAL_REGISTRY_INAD_BASE_URL}
pn.national.registries.pdnd.inad.secret = ${PN_NATIONAL_REGISTRY_INAD_PDND_CLIENT_SECRET}

# InfoCamere
pn.national.registries.inipec.connection-timeout-millis=${PN_NATIONALREGISTRIES_INIPEC_CONNECTION_TIMEOUT_MILLIS}
pn.national.registries.inipec.read-timeout-millis=${PN_NATIONALREGISTRIES_INIPEC_READ_TIMEOUT_MILLIS}

#Batch pec request configuration
pn.national.registries.inipec.batch.request.delay = ${PN_NATIONALREGISTRIES_INIPEC_BATCH_REQUEST_DELAY:${PN_NATIONALREGISTRIES_INIPEC_BATCH_DELAY:5000}}
pn.national-registries.inipec.batch.request.lock-at-most=${PN_NATIONALREGISTRIES_INIPEC_BATCH_REQUEST_LOCK_AT_MOST:27000}
pn.national-registries.inipec.batch.request.lock-at-least=${PN_NATIONALREGISTRIES_INIPEC_BATCH_REQUEST_LOCK_AT_LEAST:22000}

#Batch pec polling configuration
pn.national-registries.inipec.batch.polling.delay = ${PN_NATIONALREGISTRIES_INIPEC_BATCH_POLLING_DELAY:${PN_NATIONALREGISTRIES_INIPEC_BATCH_DELAY:30000}}
pn.national-registries.inipec.batch.polling.lock-at-most=${PN_NATIONALREGISTRIES_INIPEC_BATCH_POLLING_LOCK_AT_MOST:27000}
pn.national-registries.inipec.batch.polling.lock-at-least=${PN_NATIONALREGISTRIES_INIPEC_BATCH_POLLING_LOCK_AT_LEAST:22000}

#Batch pec recovery request configuration
pn.national-registries.inipec.batch.request.recovery.delay = ${PN_NATIONALREGISTRIES_INIPEC_BATCH_REQUEST_RECOVERY_DELAY:${PN_NATIONALREGISTRIES_INIPEC_BATCH_DELAY:30000}}
pn.national-registries.inipec.batch.request.recovery.lock-at-most=${PN_NATIONALREGISTRIES_INIPEC_BATCH_REQUEST_RECOVERY_LOCK_AT_MOST:30000}
pn.national-registries.inipec.batch.request.recovery.lock-at-least=${PN_NATIONALREGISTRIES_INIPEC_BATCH_REQUEST_RECOVERY_LOCK_AT_LEAST:1000}

#Batch pec recovery batch polling configuration
pn.national-registries.inipec.batch.polling.recovery.delay = ${PN_NATIONALREGISTRIES_INIPEC_BATCH_POLLING_RECOVERY_DELAY:${PN_NATIONALREGISTRIES_INIPEC_BATCH_DELAY:30000}}
pn.national-registries.inipec.batch.polling.recovery.lock-at-most=${PN_NATIONALREGISTRIES_INIPEC_BATCH_POLLING_RECOVERY_LOCK_AT_MOST:30000}
pn.national-registries.inipec.batch.polling.recovery.lock-at-least=${PN_NATIONALREGISTRIES_INIPEC_BATCH_POLLING_RECOVERY_LOCK_AT_LEAST:1000}

#Batch pec send to SQS configuration
pn.national-registries.inipec.batch.sqs.recovery.delay = ${PN_NATIONALREGISTRIES_INIPEC_BATCH_SQS_RECOVERY_DELAY:${PN_NATIONALREGISTRIES_INIPEC_BATCH_DELAY:30000}}
pn.national-registries.inipec.batch.sqs.recovery.lock-at-most=${PN_NATIONALREGISTRIES_INIPEC_BATCH_SQS_RECOVERY_LOCK_AT_MOST:30000}
pn.national-registries.inipec.batch.sqs.recovery.lock-at-least=${PN_NATIONALREGISTRIES_INIPEC_BATCH_SQS_RECOVERY_LOCK_AT_LEAST:1000}

# IPA
pn.national.registries.ipa.base-path = ${PN_NATIONAL_REGISTRY_IPA_BASE_URL}
pn.national.registries.ipa.secret = ${PN_NATIONAL_REGISTRY_IPA_SECRET}

# GATEWAY
pn.national.registries.sqs.input.queue.name = ${PN_NATIONALREGISTRIES_INPUT_QUEUE_NAME}

management.endpoints.web.exposure.include=health,metrics,loggers