AWSTemplateFormatVersion: 2010-09-09
Description: 'Example microservice deploy'

Transform:
  - UpdateDeploymentTransform

Parameters:
  NationalRegistryGatewayOutputsQueueName:
    Type: String
    Description: 'The name of the queue'

  NationalRegistryGatewayOutputsQueueARN:
    Type: String
    Description: 'Identify the resource that the policy applies to.'

  ProjectName:
    Type: String
    Description: 'Usually pn can be pnXYZ where XYZ are the feature number, useful to create
      experimental environments without crash official development environment'
  
  AlarmSNSTopicArn:
    Type: String
    Description: ARN of alarm topic

  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Kinesis stream that receive logs'

  ContainerImageUri:
    Type: String
    Description: 'Exact container image URI with full repository and image digest'

  MicroserviceNumber:
    Type: Number
    Description: 'Disambiguation useful for load balancer rules'

  TemplateBucketBaseUrl:
    Type: String
    Description: 'The S3 bucket from which to fetch the templates used by this stack.'

  ECSClusterName:
    Type: String
    Description: 'The name of the ECS cluster where the microservice is going to be deployed'

  SubnetsIds:
    Type: String
    Description: 'subnets ids comma separated list. Where to deploy the microservice'

  VpcId:
    Type: String
    Description: 'VpcId where the microservice is going to be deployed'

  SelcpgApiDnsName:
    Type: String
    Description: 'The DNS name used for SELC-PG rest API'
  
  EcsDefaultSecurityGroup:
    Type: String
    Description: 'Default security group required by infrastructure'

  ApplicationLoadBalancerListenerArn:
    Type: String
    Description: 'Load balancer listener where HTTP endpoints is going to be registered'

  ApplicationLoadBalancerDomain:
    Type: String
    Description: 'Base URL of the load balancer where the service is going to be reachable'

  NetworkLoadBalancerLink:
    Type: String
    Description: 'network load balancer link for API-GW'
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  PDNDBaseURL:
    Type: String
    Description: 'PDND Base URL'

  ANPRBaseURL:
    Type: String
    Description: 'ANPR Base URL'

  ANPRPurposeId:
    Type: String
    Description: 'ANPR Base Purpose ID'

  AgenziaEntrateBaseURL:
    Type: String
    Description: 'Agenzia Entrate Base URL'

  AgenziaEntratePurposeId:
    Type: String
    Description: 'Agenzia Entrate Purpose ID'

  INADBaseURL:
    Type: String
    Description: 'INAD Base URL'

  INADPurposeId:
    Type: String
    Description: 'INAD Purpose ID'

  InfoCamereBaseURL:
    Type: String
    Description: 'INIPEC Base URL'

  InfoCamereClientId:
    Type: String
    Description: 'INIPEC Client ID'

  # Parametro obbligatorio (ARN del secret)
  ANPRSSLSecret:
    Type: String
    Description: 'ANPR SecretName'

  # Parametro obbligatorio (ARN del secret)
  PDNDANPRSecret:
    Type: String
    Description: 'PDND ANPR Client assertion claims'

  # Parametro obbligatorio (ARN del secret)
  PDNDCheckCfSecret:
    Type: String
    Description: 'PDND CheckCf Client assertion claims'

  # Parametro obbligatorio (ARN del secret)
  PDNDInadSecret:
    Type: String
    Description: 'PDND INAD Client assertion claims'

  # Parametro obbligatorio (ARN del secret)
  PDNDANPRIntegritySecret:
    Type: String
    Description: 'PDND ANPR Integrity certs'

  # Parametro obbligatorio (ARN del secret)
  InfoCamereAuthSecret:
    Type: String
    Description: 'INIPEC auth cert'

  PDNDSessionTokenSigningKeyARN:
    Type: String
    Description: 'PDND Session Token Signing Key for eservice C001'

  CheckCfPDNDSessionTokenSigningKeyARN:
    Type: String
    Description: 'PDND Session Token Signing Key for eservice B001'

  InadPDNDSessionTokenSigningKeyARN:
    Type: String
    Description: 'PDND Session Token Signing Key for eservice INAD'

  PnBatchRequestEncryptKeyARN:
    Type: String
    Description: 'ARN Key DynamoDB batchRequest table'

  ANPRTipoInvio:
    Type: String
    Description: 'Input parameter for eservice C001'

  CounterTableArn:
    Type: String
    Description: 'ARN of DynamoDB table containing eservice counter information'

  BatchRequestTableArn:
    Type: String
    Description: 'ARN of DynamoDB table BatchRequest'

  BatchPollingTableArn:
    Type: String
    Description: 'ARN of DynamoDB table BatchPolling'

  PnCxIdValidationEnabled:
    Type: String
    Description: 'Validazione del pn-national-registries cx id'

Resources:

  # PN-National-Registry microservice
  NationalRegistryMicroservice:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/ecs-service.yaml"
      Parameters:
        HealthCheckPath: /actuator/health
        HealthCheckTimeout: 15
        AutoscalingStrategy: REST-API
        AutoscalingThreshold: 70
        MicroServiceUniqueName: !Sub '${ProjectName}-NationalRegistry'
        CpuValue: 1024
        MemoryAmount: 2GB
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        ContainerImageURI: !Sub '${ContainerImageUri}'
        ContainerEnvEntry1: !Sub 'AWS_REGION=${AWS::Region}'
        ContainerEnvEntry2: !Sub 'PN_NATIONAL_REGISTRY_PDND_BASE_URL=${PDNDBaseURL}'
        ContainerEnvEntry3: !Sub 'PN_NATIONAL_REGISTRY_ANPR_BASE_URL=${ANPRBaseURL}'
        ContainerEnvEntry4: !Sub 'PN_NATIONAL_REGISTRY_AGENZIA_ENTRATE_BASE_URL=${AgenziaEntrateBaseURL}'
        ContainerEnvEntry5: !Sub 'PN_NATIONAL_REGISTRY_INAD_BASE_URL=${INADBaseURL}'
        ContainerEnvEntry6: !Sub 'PN_NATIONAL_REGISTRY_INFOCAMERE_BASE_URL=${InfoCamereBaseURL}'
        ContainerEnvEntry7: !Sub 'PN_NATIONAL_REGISTRY_ANPR_PURPOSE_ID=${ANPRPurposeId}'
        ContainerEnvEntry8: !Sub 'PN_NATIONAL_REGISTRY_AGENZIA_ENTRATE_PURPOSE_ID=${AgenziaEntratePurposeId}'
        ContainerEnvEntry9: !Sub 'PN_NATIONAL_REGISTRY_INAD_PURPOSE_ID=${INADPurposeId}'
        ContainerEnvEntry10: !Sub 'PN_NATIONAL_REGISTRY_INFOCAMERE_CLIENT_ID=${InfoCamereClientId}'
        ContainerEnvEntry11: !Sub 'PN_NATIONAL_REGISTRY_ANPR_AUTH_SECRET=${ANPRSSLSecret}'
        ContainerEnvEntry12: !Sub 'PN_NATIONAL_REGISTRY_ANPR_INTEGRITY_SECRET=${PDNDANPRIntegritySecret}'
        ContainerEnvEntry13: !Sub 'PN_NATIONAL_REGISTRY_INFOCAMERE_AUTH_SECRET=${InfoCamereAuthSecret}'
        ContainerEnvEntry14: !Sub 'PN_NATIONAL_REGISTRY_ANPR_TIPO_INVIO=${ANPRTipoInvio}'
        ContainerEnvEntry15: !Sub 'PN_NATIONAL_REGISTRY_INIPEC_QUEUE_NAME=${NationalRegistryGatewayOutputsQueueName}'
        ContainerEnvEntry16: !Sub 'PN_NATIONAL_REGISTRY_VAL_CX_ID_ENABLED=${PnCxIdValidationEnabled}'
        MappedPaths: '/national-registries-private/*'
        ECSClusterName: !Ref ECSClusterName
        Subnets: !Ref SubnetsIds
        VpcId: !Ref VpcId
        EcsDefaultSecurityGroup: !Ref EcsDefaultSecurityGroup
        LoadBalancerListenerArn: !Ref ApplicationLoadBalancerListenerArn
        LoadbalancerRulePriority: !Ref MicroserviceNumber
        TaskRoleManagedPolicyArn: !Ref NationalRegistryMicroserviceTaskManagedPolicy

  NationalRegistryMicroserviceTaskManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      #PolicyName: !Sub '${ProjectName}-NationalRegistryMicroserviceSecretsPolicy'
      #Roles:
      #  - !GetAtt NationalRegistryMicroservice.Outputs.TaskRoleName
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !Ref PDNDANPRIntegritySecret
              - !Ref PDNDANPRSecret
              - !Ref ANPRSSLSecret
              - !Ref PDNDCheckCfSecret
              - !Ref PDNDInadSecret
              - !Ref InfoCamereAuthSecret
          - Effect: Allow
            Action:
              - kms:Sign
            Resource:
              - !Ref PDNDSessionTokenSigningKeyARN
              - !Ref CheckCfPDNDSessionTokenSigningKeyARN
              - !Ref InadPDNDSessionTokenSigningKeyARN
          - Effect: Allow
            Action:
              - kms:Encrypt
              - kms:Decrypt
            Resource:
              - !Ref PnBatchRequestEncryptKeyARN
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:UpdateItem
              - dynamodb:PutItem
            Resource:
              - !Ref CounterTableArn
              - !Ref BatchRequestTableArn
              - !Ref BatchPollingTableArn
              - !Sub '${BatchRequestTableArn}/index/*'
              - !Sub '${BatchPollingTableArn}/index/*'
  # NationalRegistryGatewayOutputsQueuePolicy:
  #   Type: AWS::IAM::Policy
  #   Properties:
  #     PolicyName: !Sub '${ProjectName}-NationalRegistryGatewayOutputsQueuePolicy'
  #     Roles:
  #       - !GetAtt NationalRegistryMicroservice.Outputs.TaskRoleName
  #     PolicyDocument:
  #       Version: 2012-10-17
  #       Statement:
          - Effect: Allow
            Action:
              - sqs:SendMessage
              - sqs:GetQueueUrl
            Resource:
              - !Ref NationalRegistryGatewayOutputsQueueARN

#  NationalRegistryApiGateway:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-expose-service.yaml"
#      Parameters:
#        MicroServiceUniqueName: !Sub '${ProjectName}-NationalRegistry'
#        IntendedUsage: PNPG
#        DnsName: !Ref SelcpgApiDnsName
#        ProjectName: !Ref ProjectName
#        ServiceApiPath: 'national-registries-private'
#        NetworkLoadBalancerLink: !Ref NetworkLoadBalancerLink
#        ApplicationLoadBalancerDomain: !Ref ApplicationLoadBalancerDomain
#        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
#        CloudwatchLogKinesisStreamArn: !Ref LogsKinesisSourceStreamArn
#
#  NationalRegistryApiWaf:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-waf-acl.yaml"
#      Parameters:
#        WAFName: !Sub '${ProjectName}-NationalRegistry-selcpg'
#        IntendedUsage: PNPG
#        APIGatewayARNs: !GetAtt NationalRegistryApiGateway.Outputs.APIGatewayARN
