AWSTemplateFormatVersion: 2010-09-09
Description: 'Example microservice deploy'

Transform:
  - UpdateDeploymentTransform

Parameters:
  NationalRegistryGatewayOutputsQueueName:
    Type: String
    Description: 'The name of the queue'

  NationalRegistryGatewayOutputsQueueARN:
    Type: String
    Description: 'Identify the resource that the policy applies to.'

  ProjectName:
    Type: String
    Description: 'Usually pn can be pnXYZ where XYZ are the feature number, useful to create
      experimental environments without crash official development environment'
  
  AlarmSNSTopicArn:
    Type: String
    Description: ARN of alarm topic

  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Kinesis stream that receive logs'

  ContainerImageUri:
    Type: String
    Description: 'Exact container image URI with full repository and image digest'

  MicroserviceNumber:
    Type: Number
    Description: 'Disambiguation useful for load balancer rules'

  TemplateBucketBaseUrl:
    Type: String
    Description: 'The S3 bucket from which to fetch the templates used by this stack.'

  ECSClusterName:
    Type: String
    Description: 'The name of the ECS cluster where the microservice is going to be deployed'

  SubnetsIds:
    Type: String
    Description: 'subnets ids comma separated list. Where to deploy the microservice'

  VpcEgressSubnetsIds:
    Type: String
    Description: subnets where to install PN-CORE

  VpcId:
    Type: String
    Description: 'VpcId where the microservice is going to be deployed'

  SelcpgApiDnsName:
    Type: String
    Description: 'The DNS name used for SELC-PG rest API'

  EcsDefaultSecurityGroup:
    Type: String
    Description: 'Default security group required by infrastructure'

  ApplicationLoadBalancerListenerArn:
    Type: String
    Description: 'Load balancer listener where HTTP endpoints is going to be registered'

  ApplicationLoadBalancerDomain:
    Type: String
    Description: 'Base URL of the load balancer where the service is going to be reachable'

  NetworkLoadBalancerLink:
    Type: String
    Description: 'network load balancer link for API-GW'
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  IPASecret:
    Type: String
    Description: 'IPA SecretName'

  IPABaseURL:
    Type: String
    Description: 'IPA Base URL'

  PDNDBaseURL:
    Type: String
    Description: 'PDND Base URL'

  ANPRBaseURL:
    Type: String
    Description: 'ANPR Base URL'

  ANPRPurposeId:
    Type: String
    Description: 'ANPR Base Purpose ID'

  AdELegalBaseURL:
    Type: String
    Description: 'Agenzia Entrate Legale Rappresentante Base URL'

  AdECheckCfBaseURL:
    Type: String
    Description: 'Agenzia Entrate Check CF Base URL'

  AdECheckCfPurposeId:
    Type: String
    Description: 'Agenzia Entrate Purpose ID'

  INADBaseURL:
    Type: String
    Description: 'INAD Base URL'

  INADPurposeId:
    Type: String
    Description: 'INAD Purpose ID'

  InfoCamereBaseURL:
    Type: String
    Description: 'InfoCamere Base URL'

  InfoCamereClientId:
    Type: String
    Description: 'InfoCamere Client ID'

  # Parametro obbligatorio (Nome del parametro)
  AdECheckCfSSL:
    Type: String
    Description: 'CheckCF MTLS parameterName'

  AdECheckCfTrustSecret:
    Type: String
    Description: 'SSL trusted cert CheckCF SecretName'

  AnprTrustSecret:
    Type: String
    Description: 'SSL trusted cert ANPR SecretName'

  # Parametro obbligatorio (ARN del secret)
  PDNDANPRSecret:
    Type: String
    Description: 'PDND ANPR Client assertion claims'

  # Parametro obbligatorio (ARN del secret)
  PDNDAdECheckCfSecret:
    Type: String
    Description: 'PDND CheckCf Client assertion claims'

  # Parametro obbligatorio (ARN del secret)
  PDNDInadSecret:
    Type: String
    Description: 'PDND INAD Client assertion claims'

  # Parametro obbligatorio (Nome del parametro su parameterStore)
  InfoCamereAuth:
    Type: String
    Description: 'InfoCamere auth cert parameter name'

  SecretAndSSMPrefix:
    Type: String
    Description: 'Secret and Parameter name prefix'

  SecretKeyPrefix:
    Type: String
    Description: 'Secret Key name prefix'

  AnprPDNDSessionTokenSigningKeyARN:
    Type: String
    Description: 'PDND Session Token Signing Key for eservice C001'

  CheckCfPDNDSessionTokenSigningKeyARN:
    Type: String
    Description: 'PDND Session Token Signing Key for eservice B001'

  InadPDNDSessionTokenSigningKeyARN:
    Type: String
    Description: 'PDND Session Token Signing Key for eservice INAD'

  CheckCfSigningKeyARN:
    Type: String
    Description: 'CheckCf Signing Key for MTLS'

  InfoCamereSigningKeyARN:
    Type: String
    Description: 'Info Camere Signing Key'

  PnBatchRequestEncryptKeyARN:
    Type: String
    Description: 'ARN Key DynamoDB batchRequest table'

  ANPRTipoInvio:
    Type: String
    Description: 'Input parameter for eservice C001'

  CounterTableArn:
    Type: String
    Description: 'ARN of DynamoDB table containing eservice counter information'

  BatchRequestTableArn:
    Type: String
    Description: 'ARN of DynamoDB table BatchRequest'

  BatchPollingTableArn:
    Type: String
    Description: 'ARN of DynamoDB table BatchPolling'

  PnCxIdValidationEnabled:
    Type: String
    Description: 'Validazione del pn-national-registries cx id'

  PnNationalRegistriesInipecTtl:
    Type: Number
    Description: 'IniPEC TTL'
    Default: 1209600

  PnNationalRegistriesInipecBatchRequestDelay:
    Type: Number
    Description: 'IniPEC batch request delay'
    Default: 30000

  PnNationalRegistriesInipecBatchRequestRecoveryDelay:
    Type: Number
    Description: 'IniPEC batch request recovery delay'
    Default: 30000

  PnNationalRegistriesInipecBatchRequestRecoveryAfter:
    Type: Number
    Description: 'IniPEC batch request recovery after'
    Default: 3600

  PnNationalRegistriesInipecBatchRequestMaxRetry:
    Type: Number
    Description: 'IniPEC batch request max retry'
    Default: 3

  PnNationalRegistriesInipecBatchPollingDelay:
    Type: Number
    Description: 'IniPEC batch polling delay'
    Default: 30000

  PnNationalRegistriesInipecBatchPollingRecoveryDelay:
    Type: Number
    Description: 'IniPEC batch polling recovery delay'
    Default: 30000

  PnNationalRegistriesInipecBatchPollingRecoveryAfter:
    Type: Number
    Description: 'IniPEC batch polling recovery after'
    Default: 3600

  PnNationalRegistriesInipecBatchPollingMaxRetry:
    Type: Number
    Description: 'IniPEC batch polling max retry'
    Default: 3

  PnNationalRegistriesInipecBatchSqsRecoveryDelay:
    Type: Number
    Description: 'IniPEC batch SQS recovery delay'
    Default: 30000

  EcsLogGroup:
    Type: String
    Description: ECS log group name

  # Heath Check parameters
  HealthCheckInterval:
    Description: Seconds between two health check
    Type: Number
    Default: 60

  HealthCheckTimeout:
    Description: health check timeout seconds
    Type: Number
    Default: 15

  HealthyThresholdCount:
    Description: |
      The number of consecutive health checks successes required before considering 
      an unhealthy target healthy.
    Type: Number
    Default: 5

  UnhealthyThresholdCount:
    Description: |
      The number of consecutive health check failures required before considering a target unhealthy.
    Type: Number
    Default: 2

  # Instance parameters
  # 256 (.25 vCPU) - Available memory values: 0.5GB, 1GB, 2GB
  # 512 (.5 vCPU) - Available memory values: 1GB, 2GB, 3GB, 4GB
  # 1024 (1 vCPU) - Available memory values: 2GB, 3GB, 4GB, 5GB, 6GB, 7GB, 8GB
  # 2048 (2 vCPU) - Available memory values: Between 4GB and 16GB in 1GB increments
  # 4096 (4 vCPU) - Available memory values: Between 8GB and 30GB in 1GB increments
  CpuValue:
    Type: Number
    Default: 1024
    Description: Fargate virtual CPU quantity 1024 equals one vCPU

  # 0.5GB, 1GB, 2GB - Available cpu values: 256 (.25 vCPU)
  # 1GB, 2GB, 3GB, 4GB - Available cpu values: 512 (.5 vCPU)
  # 2GB, 3GB, 4GB, 5GB, 6GB, 7GB, 8GB - Available cpu values: 1024 (1 vCPU)
  # Between 4GB and 16GB in 1GB increments - Available cpu values: 2048 (2 vCPU)
  # Between 8GB and 30GB in 1GB increments - Available cpu values: 4096 (4 vCPU)
  MemoryAmount:
    Type: String
    Default: 2GB
    Description: memory amount reserved to the task pod.
    AllowedValues: [ 2GB, 4GB, 6GB, 8GB ]

  # Autoscaling parameters
  AutoscalingCheckPeriod:
    Default: 60
    Type: Number
    Description: minimum autoscaling number of tasks\

  AutoscalingDataPointN:
    Default: 1
    Type: Number
    Description: activate when N datapoint on M

  AutoscalingDataPointM:
    Default: 1
    Type: Number
    Description: activate when N datapoint on M

  AutoscalingThreshold:
    Default: 70
    Type: String

  MinTasksNumber:
    Default: 1
    Type: Number
    Description: minimum autoscaling number of tasks

  MaxTasksNumber:
    Default: 6
    Type: Number
    Description: maximum autoscaling number of tasks 

  LogAlarmStrategy:
    Type: String
    Default: 'FATAL'
Resources:

  # PN-National-Registry microservice
  NationalRegistryMicroservice:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/ecs-service.yaml"
      Parameters:
        CpuValue: !Ref CpuValue
        MemoryAmount: !Ref MemoryAmount
        HealthCheckTimeout: !Ref HealthCheckTimeout
        HealthCheckInterval: !Ref HealthCheckInterval
        HealthyThresholdCount: !Ref HealthyThresholdCount
        UnhealthyThresholdCount: !Ref UnhealthyThresholdCount
        AutoscalingThreshold: !Ref AutoscalingThreshold
        AutoscalingCheckPeriod: !Ref AutoscalingCheckPeriod
        MinTasksNumber: !Ref MinTasksNumber
        MaxTasksNumber: !Ref MaxTasksNumber
        AutoscalingDataPointN: !Ref AutoscalingDataPointN
        AutoscalingDataPointM: !Ref AutoscalingDataPointM
        HealthCheckPath: /actuator/health
        AutoscalingStrategy: REST-API
        MicroServiceUniqueName: !Sub '${ProjectName}-national-registries'
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        ContainerImageURI: !Sub '${ContainerImageUri}'
        ContainerEnvEntry1: !Sub 'AWS_REGION=${AWS::Region}'
        ContainerEnvEntry2: !Sub 'PN_NATIONAL_REGISTRY_PDND_BASE_URL=${PDNDBaseURL}'
        ContainerEnvEntry3: !Sub 'PN_NATIONAL_REGISTRY_ANPR_BASE_URL=${ANPRBaseURL}'
        ContainerEnvEntry6: !Sub 'PN_NATIONAL_REGISTRY_ANPR_PURPOSE_ID=${ANPRPurposeId}'
        ContainerEnvEntry7: !Sub 'PN_NATIONAL_REGISTRY_ANPR_PDND_CLIENT_SECRET=${PDNDANPRSecret}'
        ContainerEnvEntry8: !Sub 'PN_NATIONAL_REGISTRY_ANPR_TIPO_INVIO=${ANPRTipoInvio}'
        ContainerEnvEntry9: !Sub 'PN_NATIONAL_REGISTRY_ADE_LEGAL_BASE_URL=${AdELegalBaseURL}'
        ContainerEnvEntry10: !Sub 'PN_NATIONAL_REGISTRY_ADE_CHECK_CF_BASE_URL=${AdECheckCfBaseURL}'
        ContainerEnvEntry11: !Sub 'PN_NATIONAL_REGISTRY_ADE_CHECK_CF_AUTH=${AdECheckCfSSL}'
        ContainerEnvEntry12: !Sub 'PN_NATIONAL_REGISTRY_ADE_CHECK_CF_PURPOSE_ID=${AdECheckCfPurposeId}'
        ContainerEnvEntry13: !Sub 'PN_NATIONAL_REGISTRY_ADE_CHECK_CF_PDND_CLIENT_SECRET=${PDNDAdECheckCfSecret}'
        ContainerEnvEntry14: !Sub 'PN_NATIONAL_REGISTRY_INAD_BASE_URL=${INADBaseURL}'
        ContainerEnvEntry15: !Sub 'PN_NATIONAL_REGISTRY_INAD_PURPOSE_ID=${INADPurposeId}'
        ContainerEnvEntry16: !Sub 'PN_NATIONAL_REGISTRY_INAD_PDND_CLIENT_SECRET=${PDNDInadSecret}'
        ContainerEnvEntry17: !Sub 'PN_NATIONAL_REGISTRY_INFOCAMERE_BASE_URL=${InfoCamereBaseURL}'
        ContainerEnvEntry18: !Sub 'PN_NATIONAL_REGISTRY_INFOCAMERE_CLIENT_ID=${InfoCamereClientId}'
        ContainerEnvEntry19: !Sub 'PN_NATIONAL_REGISTRY_INFOCAMERE_AUTH=${InfoCamereAuth}'
        ContainerEnvEntry20: !Sub 'PN_NATIONAL_REGISTRY_OUTPUT_QUEUE_NAME=${NationalRegistryGatewayOutputsQueueName}'
        ContainerEnvEntry21: !Sub 'PN_NATIONAL_REGISTRY_VAL_CX_ID_ENABLED=${PnCxIdValidationEnabled}'
        ContainerEnvEntry22: !Sub 'PN_NATIONAL_REGISTRY_IPA_BASE_URL=${IPABaseURL}'
        ContainerEnvEntry23: !Sub 'PN_NATIONAL_REGISTRY_IPA_SECRET=${IPASecret}'
        ContainerEnvEntry24: !Sub 'PN_NATIONAL_REGISTRY_INIPEC_TTL=${PnNationalRegistriesInipecTtl}'
        ContainerEnvEntry25: !Sub 'PN_NATIONAL_REGISTRY_INIPEC_BATCH_REQUEST_DELAY=${PnNationalRegistriesInipecBatchRequestDelay}'
        ContainerEnvEntry26: !Sub 'PN_NATIONAL_REGISTRY_INIPEC_BATCH_REQUEST_RECOVERY_DELAY=${PnNationalRegistriesInipecBatchRequestRecoveryDelay}'
        ContainerEnvEntry27: !Sub 'PN_NATIONAL_REGISTRY_INIPEC_BATCH_REQUEST_RECOVERY_AFTER=${PnNationalRegistriesInipecBatchRequestRecoveryAfter}'
        ContainerEnvEntry28: !Sub 'PN_NATIONAL_REGISTRY_INIPEC_BATCH_REQUEST_MAX_RETRY=${PnNationalRegistriesInipecBatchRequestMaxRetry}'
        ContainerEnvEntry29: !Sub 'PN_NATIONAL_REGISTRY_INIPEC_BATCH_POLLING_DELAY=${PnNationalRegistriesInipecBatchPollingDelay}'
        ContainerEnvEntry30: !Sub 'PN_NATIONAL_REGISTRY_INIPEC_BATCH_POLLING_RECOVERY_DELAY=${PnNationalRegistriesInipecBatchPollingRecoveryDelay}'
        ContainerEnvEntry31: !Sub 'PN_NATIONAL_REGISTRY_INIPEC_BATCH_POLLING_RECOVERY_AFTER=${PnNationalRegistriesInipecBatchPollingRecoveryAfter}'
        ContainerEnvEntry32: !Sub 'PN_NATIONAL_REGISTRY_INIPEC_BATCH_POLLING_MAX_RETRY=${PnNationalRegistriesInipecBatchPollingMaxRetry}'
        ContainerEnvEntry33: !Sub 'PN_NATIONAL_REGISTRY_INIPEC_BATCH_SQS_RECOVERY_DELAY=${PnNationalRegistriesInipecBatchSqsRecoveryDelay}'
        ContainerEnvEntry34: !Sub 'PN_NATIONAL_REGISTRY_ADE_CHECK_CF_TRUST_SECRET=${AdECheckCfTrustSecret}'
        ContainerEnvEntry35: !Sub 'PN_NATIONAL_REGISTRY_ANPR_TRUST_SECRET=${AnprTrustSecret}'

        # MicroServiceSecretAndSSMPrefix: !Sub '${SecretAndSSMPrefix}'
        MappedPaths: '/national-registries-private/*'
        ECSClusterName: !Ref ECSClusterName
        Subnets: !Ref VpcEgressSubnetsIds
        VpcId: !Ref VpcId
        EcsDefaultSecurityGroup: !Ref EcsDefaultSecurityGroup
        LoadBalancerListenerArn: !Ref ApplicationLoadBalancerListenerArn
        LoadbalancerRulePriority: !Ref MicroserviceNumber
        TaskRoleManagedPolicyArn: !Ref NationalRegistryMicroserviceTaskManagedPolicy
        EcsLogGroup: !Ref EcsLogGroup
        LogAlarmStrategyV1: !Ref LogAlarmStrategy

  NationalRegistryMicroserviceTaskManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !Sub 'arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretAndSSMPrefix}*'
              - !Sub 'arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretKeyPrefix}*'
          - Effect: Allow
            Action:
              - kms:Sign
            Resource:
              - !Ref AnprPDNDSessionTokenSigningKeyARN
              - !Ref CheckCfPDNDSessionTokenSigningKeyARN
              - !Ref InadPDNDSessionTokenSigningKeyARN
              - !Ref CheckCfSigningKeyARN
              - !Ref InfoCamereSigningKeyARN
          - Effect: Allow
            Action:
              - kms:Encrypt
              - kms:Decrypt
            Resource:
              - !Ref PnBatchRequestEncryptKeyARN
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:UpdateItem
              - dynamodb:PutItem
            Resource:
              - !Ref CounterTableArn
              - !Ref BatchRequestTableArn
              - !Ref BatchPollingTableArn
              - !Sub '${BatchRequestTableArn}/index/*'
              - !Sub '${BatchPollingTableArn}/index/*'
          - Effect: Allow
            Action:
              - sqs:SendMessage
              - sqs:GetQueueUrl
            Resource:
              - !Ref NationalRegistryGatewayOutputsQueueARN
          - Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
            Resource:
              - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/MapTaxIdWhiteList'
              - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${SecretAndSSMPrefix}/*'

  NationalRegistryApiGateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-expose-service.yaml"
      Parameters:
        MicroServiceUniqueName: !Sub '${ProjectName}-national-registries'
        IntendedUsage: PNPG
        DnsName: !Ref SelcpgApiDnsName
        ProjectName: !Ref ProjectName
        ServiceApiPath: 'national-registries-private'
        NetworkLoadBalancerLink: !Ref NetworkLoadBalancerLink
        ApplicationLoadBalancerDomain: !Ref ApplicationLoadBalancerDomain
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        CloudwatchLogKinesisStreamArn: !Ref LogsKinesisSourceStreamArn

  NationalRegistryApiWaf:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-waf-acl.yaml"
      Parameters:
        WAFName: !Sub '${ProjectName}-national-registries-pnpg'
        IntendedUsage: PNPG
        APIGatewayARNs: !GetAtt NationalRegistryApiGateway.Outputs.APIGatewayARN
