AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send Logs'

  LogRetention:
    Type: Number
    Default: 14

  AlarmSNSTopicName:
    Type: String

Resources:
  ###      KEY PAIR PER CREARE JWT NECESSARIO PER ACCEDERE AI SERVIZI M2M DI PDND    ###
  ###   La chiave viene impiegata per firmare il client assertion che serve          ###
  ###   per richedere a PDND il JWT da utilizzare per invocare i servizi M2M di PDND ###
  ######################################################################################
  PnBatchRequestEncryptKey:
    Type: 'AWS::KMS::Key'
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Description: Symmetric default key to encrypt table
      KeySpec: SYMMETRIC_DEFAULT
      KeyUsage: ENCRYPT_DECRYPT
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'

  # AnprPDNDSessionTokenSigningKey:
  #   Type: 'AWS::KMS::Key'
  #   DeletionPolicy: Retain
  #   UpdateReplacePolicy: Retain
  #   Properties:
  #     Description: RSA-2048 key to generate session token
  #     KeySpec: RSA_2048
  #     KeyUsage: SIGN_VERIFY
  #     KeyPolicy:
  #       Version: 2012-10-17
  #       Statement:
  #         - Sid: Enable IAM User Permissions
  #           Effect: Allow
  #           Principal:
  #             AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
  #           Action: 'kms:*'
  #           Resource: '*'

  # # Application use this alias to access the public/private key pair
  # AnprPDNDSessionTokenSigningKeyAlias:
  #   Type: 'AWS::KMS::Alias'
  #   Properties:
  #     AliasName: !Sub 'alias/${ProjectName}-national-registries-anpr-pdnd'
  #     TargetKeyId: !Ref AnprPDNDSessionTokenSigningKey

  # CheckCfPDNDSessionTokenSigningKey:
  #   Type: 'AWS::KMS::Key'
  #   DeletionPolicy: Retain
  #   UpdateReplacePolicy: Retain
  #   Properties:
  #     Description: RSA-2048 key to generate session token
  #     KeySpec: RSA_2048
  #     KeyUsage: SIGN_VERIFY
  #     KeyPolicy:
  #       Version: 2012-10-17
  #       Statement:
  #         - Sid: Enable IAM User Permissions
  #           Effect: Allow
  #           Principal:
  #             AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
  #           Action: 'kms:*'
  #           Resource: '*'

  #   # Application use this alias to access the public/private key pair
  # CheckCfPDNDSessionTokenSigningKeyAlias:
  #   Type: 'AWS::KMS::Alias'
  #   Properties:
  #     AliasName: !Sub 'alias/${ProjectName}-national-registries-check-cf-pdnd'
  #     TargetKeyId: !Ref CheckCfPDNDSessionTokenSigningKey

  # InadPDNDSessionTokenSigningKey:
  #   Type: 'AWS::KMS::Key'
  #   DeletionPolicy: Retain
  #   UpdateReplacePolicy: Retain
  #   Properties:
  #     Description: RSA-2048 key to generate session token
  #     KeySpec: RSA_2048
  #     KeyUsage: SIGN_VERIFY
  #     KeyPolicy:
  #       Version: 2012-10-17
  #       Statement:
  #         - Sid: Enable IAM User Permissions
  #           Effect: Allow
  #           Principal:
  #             AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
  #           Action: 'kms:*'
  #           Resource: '*'

  # # Application use this alias to access the public/private key pair
  # InadPDNDSessionTokenSigningKeyAlias:
  #   Type: 'AWS::KMS::Alias'
  #   Properties:
  #     AliasName: !Sub 'alias/${ProjectName}-national-registries-inad-pdnd'
  #     TargetKeyId: !Ref InadPDNDSessionTokenSigningKey

  # CheckCfSigningKey:
  #   Type: 'AWS::KMS::Key'
  #   DeletionPolicy: Retain
  #   UpdateReplacePolicy: Retain
  #   Properties:
  #     Description: RSA-2048 key to generate session token
  #     KeySpec: RSA_2048
  #     KeyUsage: SIGN_VERIFY
  #     KeyPolicy:
  #       Version: 2012-10-17
  #       Statement:
  #         - Sid: Enable IAM User Permissions
  #           Effect: Allow
  #           Principal:
  #             AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
  #           Action: 'kms:*'
  #           Resource: '*'

  #   # Application use this alias to access the public/private key pair
  # CheckCfSigningKeyAlias:
  #   Type: 'AWS::KMS::Alias'
  #   Properties:
  #     AliasName: !Sub 'alias/${ProjectName}-national-registries-check-cf'
  #     TargetKeyId: !Ref CheckCfSigningKey

  # InfoCamereSigningKey:
  #   Type: 'AWS::KMS::Key'
  #   DeletionPolicy: Retain
  #   UpdateReplacePolicy: Retain
  #   Properties:
  #     Description: RSA-2048 key to generate session token
  #     KeySpec: RSA_2048
  #     KeyUsage: SIGN_VERIFY
  #     KeyPolicy:
  #       Version: 2012-10-17
  #       Statement:
  #         - Sid: Enable IAM User Permissions
  #           Effect: Allow
  #           Principal:
  #             AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
  #           Action: 'kms:*'
  #           Resource: '*'

  # Application use this alias to access the public/private key pair
  # InfoCamereSigningKeyAlias:
  #   Type: 'AWS::KMS::Alias'
  #   Properties:
  #     AliasName: !Sub 'alias/${ProjectName}-national-registries-info-camere'
  #     TargetKeyId: !Ref InfoCamereSigningKey

  CounterTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain 
    Properties:
      TableName: !Sub '${ProjectName}-counter'
      AttributeDefinitions:
        - AttributeName: "eservice"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "eservice"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true   
        
  BatchRequestTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain 
    Properties:
      TableName: !Sub '${ProjectName}-batchRequests'
      AttributeDefinitions:
        - AttributeName: "correlationId"
          AttributeType: "S"
        - AttributeName: "batchId"
          AttributeType: "S"
        - AttributeName: "status"
          AttributeType: "S"
        - AttributeName: "lastReserved"
          AttributeType: "S"
        - AttributeName: "sendStatus"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "correlationId"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "batchId-lastReserved-index"
          KeySchema:
            - AttributeName: batchId
              KeyType: HASH
            - AttributeName: lastReserved
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: "status-index"
          KeySchema:
            - AttributeName: status
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: "sendStatus-lastReserved-index"
          KeySchema:
            - AttributeName: sendStatus
              KeyType: HASH
            - AttributeName: lastReserved
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      BillingMode: "PAY_PER_REQUEST"
      SSESpecification:
        KMSMasterKeyId: !Ref PnBatchRequestEncryptKey
        SSEEnabled: true
        SSEType: KMS
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true           

  BatchPollingTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain 
    Properties:
      TableName: !Sub '${ProjectName}-batchPolling'
      AttributeDefinitions:
        - AttributeName: "batchId"
          AttributeType: "S"
        - AttributeName: "status"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "batchId"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "status-index"
          KeySchema:
            - AttributeName: status
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true         

  PnNationalRegistriesLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain 
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub '${ProjectName}-national-registries'
        LogGroupRetention: !Ref LogRetention
        LogsKinesisSourceStreamArn: !Ref LogsKinesisSourceStreamArn

  PnNationalRegistriesCertificateDLQ:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain    
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-national_registries_certificate_DLQ'
        DelaySeconds: 1
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        HasDLQ:  "false"
        QueueHasAlarm:  "true"

  # Coda per interna per memorizzare richieste al gateway
  # NB: usati i valori di default per: DelaySeconds, DeadLetterQueueName, MessageRetentionPeriod, MaxReceiveCount, DeadLetterMessageRetentionPeriod,
  PnNationalRegistryGatewayInputsQueue:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-national_registry_gateway_inputs'
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        VisibilityTimeout: 300
        MaxReceiveCount: 10
        DelaySeconds: 1

  GatewayRequestTrackerTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-gatewayRequestTracker'
      AttributeDefinitions:
        - AttributeName: "correlationId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "correlationId"
          KeyType: "HASH"
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # Altra coda interna per gestire le richieste al gateway relative alla fase di validazione di una notifica
  # di conseguenza più allertata per i messaggi di errore.
  PnNationalRegistryValidationGatewayInputsQueue:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-national_registry_validation_gateway_inputs'
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        VisibilityTimeout: 300
        MaxReceiveCount: 10
        DelaySeconds: 1
        OncallQueueDlqOldestAgeLimit: 7200

#Necessario a causa di bug script deploy
Outputs:
  PnBatchRequestEncryptKeyARN:
    Description: PnBatchRequestEncryptKeyARN
    Value: !Sub '${PnBatchRequestEncryptKey.Arn}'
  # AnprPDNDSessionTokenSigningKeyARN:
  #   Description: AnprPDNDSessionTokenSigningKeyARN
  #   Value: !Sub '${AnprPDNDSessionTokenSigningKey.Arn}'
  # CheckCfPDNDSessionTokenSigningKeyARN:
  #   Description: CheckCfPDNDSessionTokenSigningKeyARN
  #   Value: !Sub '${CheckCfPDNDSessionTokenSigningKey.Arn}'
  # InadPDNDSessionTokenSigningKeyARN:
  #   Description: InadPDNDSessionTokenSigningKeyARN
  #   Value: !Sub '${InadPDNDSessionTokenSigningKey.Arn}'
  # CheckCfSigningKeyARN:
  #   Description: CheckCfSigningKeyARN
  #   Value: !Sub '${CheckCfSigningKey.Arn}'
  # CheckCfSigningKeyId:
  #   Description: CheckCfSigningKeyARN
  #   Value: !Ref CheckCfSigningKey
  # InfoCamereSigningKeyARN:
  #   Description: InfoCamereSigningKeyARN
  #   Value: !Sub '${InfoCamereSigningKey.Arn}'
  # InfoCamereSigningKeyId:
  #   Value: !Ref InfoCamereSigningKey
  CounterTableArn:
    Description: ARN Dynamo Name used by application to access the key-value store of CounterTable
    Value: !Sub '${CounterTable.Arn}'
  BatchRequestTableArn:
    Description: ARM Dynamo Name used by application to access the key-value store of BatchRequestTable
    Value: !Sub '${BatchRequestTable.Arn}'
  BatchPollingTableArn:
    Description: ARM Dynamo Name used by application to access the key-value store of BatchPollingTable
    Value: !Sub '${BatchPollingTable.Arn}'

  # Log group exports
  EcsLogGroup:
    Value: !GetAtt PnNationalRegistriesLogGroup.Outputs.LogGroupName


  # National Registries Certificate renewal alarm DLQ
  PnNationalRegistriesCertificateDLQName:
    Value: !GetAtt PnNationalRegistriesCertificateDLQ.Outputs.QueueName
  PnNationalRegistriesCertificateDLQURL:
    Value: !GetAtt PnNationalRegistriesCertificateDLQ.Outputs.QueueURL
  PnNationalRegistriesCertificateDLQARN:
    Value: !GetAtt PnNationalRegistriesCertificateDLQ.Outputs.QueueARN
  PnNationalRegistriesCertificateDLQAlarmARN:
    Value: !GetAtt PnNationalRegistriesCertificateDLQ.Outputs.SqsDLQAlarmArn

  # PnNationalRegistryGatewayInputs Queue
  NationalRegistryGatewayInputsQueueName:
    Value: !GetAtt PnNationalRegistryGatewayInputsQueue.Outputs.QueueName
  NationalRegistryGatewayInputsQueueARN:
    Value: !GetAtt PnNationalRegistryGatewayInputsQueue.Outputs.QueueARN
  NationalRegistryGatewayInputsDLQName:
    Value: !GetAtt PnNationalRegistryGatewayInputsQueue.Outputs.DeadLetterQueueName
  PnNationalRegistryGatewayInputsDLQURL:
    Value: !GetAtt PnNationalRegistryGatewayInputsQueue.Outputs.DeadLetterQueueURL
  NationalRegistryGatewayInputsDLQARN:
    Value: !GetAtt PnNationalRegistryGatewayInputsQueue.Outputs.DeadLetterQueueARN

  GatewayRequestTrackerTableArn:
    Description: ARN Dynamo Name used by application to access the key-value store of GatewayRequestTrackerTable
    Value: !Sub '${GatewayRequestTrackerTable.Arn}'

  # PnNationalRegistryValidationGatewayInputs Queue
  NationalRegistryValidationGatewayInputsQueueName:
    Value: !GetAtt PnNationalRegistryValidationGatewayInputsQueue.Outputs.QueueName
  NationalRegistryValidationGatewayInputsQueueARN:
    Value: !GetAtt PnNationalRegistryValidationGatewayInputsQueue.Outputs.QueueARN
  NationalRegistryValidationGatewayInputsDLQName:
    Value: !GetAtt PnNationalRegistryValidationGatewayInputsQueue.Outputs.DeadLetterQueueName
  NationalRegistryValidationGatewayInputsDLQURL:
    Value: !GetAtt PnNationalRegistryValidationGatewayInputsQueue.Outputs.DeadLetterQueueURL
  NationalRegistryValidationGatewayInputsDLQARN:
    Value: !GetAtt PnNationalRegistryValidationGatewayInputsQueue.Outputs.DeadLetterQueueARN
