AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'


Resources:
  ###      KEY PAIR PER CREARE JWT NECESSARIO PER ACCEDERE AI SERVIZI M2M DI PDND    ###
  ###   La chiave viene impiegata per firmare il client assertion che serve          ###
  ###   per richedere a PDND il JWT da utilizzare per invocare i servizi M2M di PDND ###
  ######################################################################################
  PDNDSessionTokenSigningKey:
    Type: 'AWS::KMS::Key'
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Description: RSA-2048 key to generate session token
      KeySpec: RSA_2048
      KeyUsage: SIGN_VERIFY
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'

  # Application use this alias to access the public/private key pair
  PDNDSessionTokenSigningKeyAlias:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: !Sub 'alias/${ProjectName}-national-registries-pdnd'
      TargetKeyId: !Ref PDNDSessionTokenSigningKey

  CheckCfPDNDSessionTokenSigningKey:
    Type: 'AWS::KMS::Key'
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Description: RSA-2048 key to generate session token
      KeySpec: RSA_2048
      KeyUsage: SIGN_VERIFY
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'

    # Application use this alias to access the public/private key pair
  CheckCfPDNDSessionTokenSigningKeyAlias:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: !Sub 'alias/${ProjectName}-national-registries-check-cf-pdnd'
      TargetKeyId: !Ref CheckCfPDNDSessionTokenSigningKey

  InadPDNDSessionTokenSigningKey:
    Type: 'AWS::KMS::Key'
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Description: RSA-2048 key to generate session token
      KeySpec: RSA_2048
      KeyUsage: SIGN_VERIFY
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'

  # Application use this alias to access the public/private key pair
  InadPDNDSessionTokenSigningKeyAlias:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: !Sub 'alias/${ProjectName}-national-registries-inad-pdnd'
      TargetKeyId: !Ref InadPDNDSessionTokenSigningKey

  QueueSqs:
    type: AWS::SQS:Queue
    Properties:
      QueueName: !Sub '${ProjectName}-inipec'
      FifoQueue: 'false'

  CounterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-counter'
      AttributeDefinitions:
        - AttributeName: "eservice"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "eservice"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"

  BatchRequestTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-batchRequests'
      AttributeDefinitions:
        - AttributeName: "correlationId"
          AttributeType: "S"
        - AttributeName: "cf"
          AttributeType: "S"
        - AttributeName: "batchId"
          AttributeType: "S"
        - AttributeName: "retry"
          AttributeType: "S"
        - AttributeName: "ttl"
          AttributeType: "S"
        - AttributeName: "status"
          AttributeType: "S"
        - AttributeName: "lastReserved"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "correlationId"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "batchId-lastReserved-index"
          KeySchema:
            - AttributeName: batchId
              KeyType: HASH
            - AttributeName: lastReserved
              KeyType: RANGE
        - IndexName: "status-index"
          KeySchema:
            - AttributeName: status
              KeyType: HASH
      BillingMode: "PAY_PER_REQUEST"

  BatchPollingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-batchPolling'
      AttributeDefinitions:
        - AttributeName: "batchId"
          AttributeType: "S"
        - AttributeName: "pollingId"
          AttributeType: "S"
        - AttributeName: "status"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "batchId"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "status-index"
          KeySchema:
            - AttributeName: status
              KeyType: HASH
      BillingMode: "PAY_PER_REQUEST"

#Necessario a causa di bug script deploy
Outputs:
  PDNDSessionTokenSigningKeyARN:
    Description: PDNDSessionTokenSigningKeyARN
    Value: !Sub '${PDNDSessionTokenSigningKey.Arn}'
  CheckCfPDNDSessionTokenSigningKeyARN:
    Description: CehckCfPDNDSessionTokenSigningKeyARN
    Value: !Sub '${CheckCfPDNDSessionTokenSigningKey.Arn}'
  InadPDNDSessionTokenSigningKeyARN:
    Description: CehckCfPDNDSessionTokenSigningKeyARN
    Value: !Sub '${InadPDNDSessionTokenSigningKey.Arn}'
  CounterTableArn:
    Description: ARN Dynamo Name used by application to access the key-value store of CounterTable
    Value: !Sub '${CounterTable.Arn}'
  BatchRequestTableArn:
    Description: ARM Dynamo Name used by application to access the key-value store of BatchRequestTable
    Value: !Sub '${BatchRequestTable.Arn}'
  BatchPollingTableArn:
    Description: ARM Dynamo Name used by application to access the key-value store of BatchPollingTable
    Value: !Sub '${BatchPollingTable.Arn}'



