/*
 * INAD - Domicilio Digitale
 * API rese disponibili da INAD al Catalogo delle API previsto nel modello di interoperabilità delle pubbliche amministrazioni.  Pattern Model applicati: - [ID_AUTH_CHANNEL_01] Direct Trust Transport-Level Security - [BLOCK_REST] Blocking REST - [NONBLOCK_PULL_REST] Not Blocking Pull REST
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package it.pagopa.pn.national.registries.model.inad;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Motivazione cessazione del Domicilio Digitale
 */
public enum MotivationTerminationDto {

    UFFICIO("CESSAZIONE_UFFICIO"),

    VOLONTARIA("CESSAZIONE_VOLONTARIA");

    private final String value;

    MotivationTerminationDto(String value) {
        this.value = value;
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
    public static MotivationTerminationDto fromValue(String value) {
        for (MotivationTerminationDto b : MotivationTerminationDto.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
}

